# Generated by Django 4.0.5 on 2022-06-17 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Book',
        ),
    ]
