# Generated by Django 4.0.5 on 2022-07-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_assignment_userassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userassignment',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
