# Generated by Django 4.0.5 on 2022-07-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_userassignment_date_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rich_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userassignment',
            name='word_index',
            field=models.IntegerField(default=0),
        ),
    ]
