# Generated by Django 4.0.5 on 2022-07-14 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0006_book_rich_text_userassignment_word_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MissedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
                ('word_index', models.IntegerField()),
                ('user_assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.userassignment')),
            ],
        ),
    ]
