# Generated by Django 4.0.5 on 2022-07-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_classroom_teacher_id_missedword'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassignment',
            name='late_exemption_granted',
            field=models.BooleanField(default=False),
        ),
    ]
