# Generated by Django 4.0.5 on 2022-07-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_userassignment_late_exemption_granted'),
    ]

    operations = [
        migrations.AddField(
            model_name='missedword',
            name='known',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
