# Generated by Django 4.0.6 on 2022-07-26 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('min_reading_level', models.PositiveSmallIntegerField(default=0)),
                ('max_reading_level', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_reading_level', models.PositiveSmallIntegerField(default=0)),
                ('max_reading_level', models.PositiveSmallIntegerField(default=0)),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_level', models.PositiveSmallIntegerField(default=0)),
                ('classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.classroom')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(default=0)),
                ('correctness_score', models.FloatField(default=0)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('word_index', models.PositiveIntegerField(default=0)),
                ('late_exemption_granted', models.BooleanField(default=False)),
                ('completion_time', models.PositiveIntegerField(default=0)),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.assignment')),
                ('student_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MissedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
                ('word_index', models.PositiveIntegerField()),
                ('known', models.BooleanField()),
                ('user_assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.userassignment')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('rich_text', models.TextField()),
                ('public', models.BooleanField(default=False)),
                ('classroom_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.classroom')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.book'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='classroom_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.classroom'),
        ),
    ]
